name: DayUtils
version: 1.0
main: me.BaddCamden.DayUtils.DayUtilsPlugin
description: Utilities for managing day and night cycles
api-version: "1.20"
commands:
  dayutils:
    description: DayUtils administrative commands
    usage: >-
      /dayutils reload | /dayutils trigger <type> [world] | /dayutils setdaylength <ticks> |
      /dayutils setnightlength <ticks> | /dayutils setspeed <multiplier> | /dayutils setnightspassed <count> [world] | /dayutils status [world]
    permission: dayutils.reload
    permission-message: You do not have permission to run this command.
permissions:
  dayutils.reload:
    description: Reload DayUtils configuration.
    default: op
  dayutils.trigger:
    description: Trigger registered custom day types.
    default: op
  dayutils.setdaylength:
    description: Configure the day length.
    default: op
  dayutils.setnightlength:
    description: Configure the night length.
    default: op
  dayutils.setspeed:
    description: Configure the day/night speed multiplier.
    default: op
  dayutils.setnightspassed:
    description: Configure the nights passed counter for a world.
    default: op
